### ISSUE TITLE
Distributed message buses

### ISSUE THREAD

**Issue by martintrojer** [malcolmsparks/up#1]
I like the the message bus architecture between the building blocks.

Have you thought about making them distributed from the get go (i.e. replace lamina with HornetQ or equivalent?)

**Comment by malcolmsparks** [comment]
I just looked at HonetQ the other day, yes it's a good idea- I'm not really
using anything in lamina other than vanilla pub/sub so this could be
something to replace

**Comment by martintrojer** [comment]
Maybe apply some OO abstractions of the message bus so it can be easily changed? :)

**Comment by malcolmsparks** [comment]
Yes, protocols :)
